module.exports = ({ env }) => ({
  // ...
  plugins: {
    // ...
    "users-permissions": {
      jwtSecret: env("JWT_SECRET", crypto.randomBytes(16).toString("base64")),
      // ...
    },
  },
  // ...
});
